### ISSUE TITLE
Project 1 Feedback from Jon Hurwitz

### ISSUE THREAD

**Issue by jdh8v** [gwsb-istm-6212-fall-2016/euhwang_istm_6212#1]
General:
• I like how you used bold formatting and variations in font size to provide headers for the various sections. This made it easy to follow.

Problem 1
• Part A
o   I got the same result you did. However, you were able to obtain your results using less lines of code by using the grep –iow command. In my code I had to do this as an additional step.
• Part B
o   I got the same result you did. However, we executed are code in a different order. It’s good to see that there are many paths to the same answer.

Problem 2
• Part A
o   I got the same results you did. I like here in your code that you point out that it can be somewhat time consuming to run, and you provided the performance stats so the reader knows what to expect. One thing I did differently here was running some preliminary queries that output the column values so that a reader understands the nature of the data being analyzed. However, this step is purely for documentation transparency, and doesn’t impact the final result. In addition, I added a preliminary step to save the sorted output as a csv file, as this seemed to be the most time consuming step.
• Part B
o   I got the same results you did. One thing different you did which I like was including the station name in your output, so it’s clear which station is being used to define the most popular location. In addition, I liked how you used csvlook when producing your output as it is a bit cleaner to view.

Problem 3
• Part A
o   Our grep commands are nearly identical and we get the same results. I noticed you changed the syntax to return 1 character words which is what I did as well. For your Python filter, I see you were able to obtain the exact matches to your grep code while I was unable to. It appears you used a function from the ‘re’ package to perform your splitting, which I did not. I’ll be sure to remember your approach next time I need to split words from a text file.
• Part B
o   Our results are slightly different because we used different stop words. However, you seem to get good results using the ‘re’ package so I will remember this next time.

Extra Credit
• I did not complete the Extra Credit portion, but I re-ran your code. In datanotebook, the time function does not appear to be supported so I removed that before running. Other than that, your code was well documented and I like how you re-used the stop-word python file for this purpose, which demonstrated the value and flexibility when you develop filters with a singular purpose.

**Comment by euhwang** [comment]
Thanks Jon!
