### ISSUE TITLE
Project 2 review

### ISSUE THREAD

**Issue by YingZhang1028** [gwsb-istm-6212-fall-2016/euhwang_istm_6212#3]
Hello Eugene,

Great job on your project 02! I can’t find any flaw in you project and your code runs perfectly.

Your star schema is wonderful, all facts tables and dimension table make sense. I learned how to use python Image module to show the diagram in jupyter notebook. I tried to find a way to display the picture in my project but can’t figure out it. 

I also saw that you used !wget to downloaded data from website directly. It is awesome! 

Thanks to your well-structured code and explicit markdown, I can understand your code well. You use UNION ALL to verify whether there is a one-to-one relationship. Your method is more accurate than mine.
 
You made lots of interesting exploration in the crime data, and added plots to show some results. I learned how to combine SQL and data frame in python to do some analysis.
 
Of course, great explanation about augmenting dimensions in bonus part.

Ying

**Comment by euhwang** [comment]
Thanks!
