### ISSUE TITLE
Project 2 review

### ISSUE THREAD

**Issue by flhuihui1001** [gwsb-istm-6212-fall-2016/euhwang_istm_6212#4]
Hi euhwang,

Firstly, congratulations on finishing this project. You've done a great job. I can completely duplicate most of the results on my computer. Here are some other details.

Pros:
1. I like your markdowns and comments that make the reader easy to follow your thoughts. I especially like the that you put the meaning of each variable into a table in the markdown. I don't know how to do that I just list all things together without formatting them. I wish I could do the same thing, would you mind sharing your experience in making a table in the markdown?
2. I Like your star schema. You set 6 dimensions, which is an incredible job! More dimensions create more opportunities to analyze the data. Your visualization of results are also quite intuitionistic. In every way, your work is quite excellent.

Cons:
1. Can't load the star schema image, maybe because the use of absolute path (I did the same). Next time, using an online URL will be better.
2. If you could delete those unnecessary codes( star with #), your work will be more neaty.

But never mind, you have already done a quite good job. The complexity of your star schema and the precious of your code are quite impressive! Congratulations again!

Regards,
Livia

**Comment by euhwang** [comment]
Thanks!
