### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by roxa12** [gwsb-istm-6212-fall-2016/euhwang_istm_6212#5]
Hi Eugene,

Looking at your work was more helpful for me, I have to say, I learned a lot from your codes and your perspective at how you dissected the information. I was able to replicate your project with no issues. Your work was very thorough. I liked the bar graphs and especially seeing the trend of crimes going down, and then isolating 2016 specifically. Your star schema is also very detailed and I like your comments about missing unique id and the need for having one. 

Overall, very good job and keep it up!

**Comment by euhwang** [comment]
Thanks!
